### ISSUE TITLE
unmet peer dependencies

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-test-utils#14]
```
warning " > prisma-test-utils@0.3.9" has unmet peer dependency "@prisma/cli@*".
warning " > prisma-test-utils@0.3.9" has unmet peer dependency "@prisma/lift@*".
warning " > prisma-test-utils@0.3.9" has unmet peer dependency "@prisma/photon@*".
```

**Comment by maticzav** [comment]
@janpio I have no idea how to tackle these. Is there a suggested approach? Should I just list them as `devDeps`?

**Comment by janpio** [comment]
Lift and Photon do not exist any more, so they can probably just be removed. 
For the CLI subpackage, not sure why that needs to be listed there.

9 months ago you probably had a reason to add them?
https://github.com/prisma/prisma-test-utils/blame/085e321baf1f571335f9a95a41faa392615e9c0b/package.json#L61-L63

**Comment by maticzav** [comment]
hmm, yeah! I think it was part of the generator structure back then. We can remove them now.

**Comment by maticzav** [comment]
fixed 🙂
