### ISSUE TITLE
TypeError e.map is not a function

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma-test-utils#29]
For the schema: https://github.com/prisma/database-schema-examples/blob/master/postgres/basic-blog/schema.sql

Logs from test-utils just before the failure: 

```
2020-03-06T21:47:40.352Z prisma-client Requests:
2020-03-06T21:47:40.353Z prisma-client [
  'mutation {\n' +
    '  createOneauthors(data: {\n' +
    '    name: "ofosid"\n' +
    '  }) {\n' +
    '    id\n' +
    '    name\n' +
    '    authors_blogs {\n' +
    '\n' +
    '    }\n' +
    '  }\n' +
    '}'
]
2020-03-06T21:47:40.425Z engine {
  error: TypeError: e.map is not a function
      at /home/runner/work/introspection-engine-output/introspection-engine-output/clients/postgresql_public_test_utils/basic-blog/runtime/index.js:1:16669
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at Dataloader.loader (/home/runner/work/introspection-engine-output/introspection-engine-output/clients/postgresql_public_test_utils/basic-blog/index.js:56:23)
}
```

This is most likely happening because `authors_blogs` model has no scalar on it and test utils produces an incorrect client call for that (empty selection set). 

@maticzav does this issue description make sense? 

---

Internal notes: 

Test utils database(s) affected: 
- https://github.com/prisma/introspection-engine-output/blob/test_utils/test-utils/results/postgresql_public_test_utils_basic-blog_stderr.log

**Comment by maticzav** [comment]
@divyenduz yup, I think this is it.

**Comment by janpio** [comment]
The log you link to @divyenduz does not show the problem from the issue.

> because `authors_blogs` model has no scalar on it

What does that mean?

**Comment by divyenduz** [comment]
> The log you link to @divyenduz does not show the problem from the issue.

I don't follow, it has the text "error: TypeError: e.map is not a function", right? 

> because authors_blogs model has no scalar on it

I meant that the model generated for this table `authors_blogs` does not have any scalar fields

```prisma 
model authors_blogs {
  author_id authors
  blog_id   blogs

  @@unique([author_id, blog_id], name: "authors_blogs_author_id_blog_id_key")
}
```

Does that make sense now?

**Comment by janpio** [comment]
> > The log you link to @divyenduz does not show the problem from the issue.
> 
> I don't follow, it has the text "error: TypeError: e.map is not a function", right?

No, the linked log does not.

**Comment by janpio** [comment]
> Does that make sense now?

No. The "Logs from test-utils just before the failure:" snippet you posted above mentions `createOneauthors`, which points to model `authors`. `authors_blogs` has an `@@unique` which means it works with P2, and I see no reason why `test-utils` should not be able to (unless there is some limitation that was not mentioned here yet).

**Comment by divyenduz** [comment]
> No, the linked log does not.

The linked logged is a link on the branch, not a permalink, its contents are subjected to change. A permalink to a failing log is [this one](https://github.com/prisma/introspection-engine-output/blob/58b672782ad7dc81372c50c2ae2cdb7881985113/test-utils/results/postgresql_public_test_utils_basic-blog_stderr.log#L62-L81). 

In the future, I will link both permalink and branch link (to check quickly, if something is fixed)

> snippet you posted above mentions createOneauthors, which points to model authors

That is (or was) the correct line of the error, let me extract the query from the logs in my first comment to explain further: 

![image](https://user-images.githubusercontent.com/746482/76403795-77483600-63ab-11ea-8ad2-fcd72f7f9f5d.png)

As you can see in this image, the generated GraphQL query for the model authors was incorrect.

**Comment by janpio** [comment]
Doesn't this mean that test-utils is creating a Prisma Client call with missing data, which gets transformed into a broken query which is then somehow causing the error in Prisma Client (probably because the QE is returning something unexpected)?

The log should include the Prisma Client call now as well. We should rerun this so we have all the context. (Related: The QE can also log all the queries it is sending, right? We should probably have that logged here as well to understand what it is trying to do)

**Comment by divyenduz** [comment]
I think this mutation log is already coming from client and not test-utils. I will post the client call here if I see it again or close this issue if this is no longer present in any logs in this form.

**Comment by janpio** [comment]
> I think this mutation log is already coming from client and not test-utils.

Yes, but I expect this to be caused by what test-utils sends into Client - not Client messing something up really.

**Comment by divyenduz** [comment]
I agree with that, hence, I created the issue here. I will clean it up as I have more information.

**Comment by divyenduz** [comment]
This issue is not present anymore on the latest run.
